- name: "Create deployment user"
  user:
    name: rails
    comment: "User for deployment rails app."
    home: /opt/rails
    system: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_comment: "Key for auth on GitHub"
  tags: [user]
