---
- name: Install aptitude
  apt:
    name: aptitude
    force: yes
    state: present
  tags: [rails]

- name: upgrade
  action: apt update_cache=yes upgrade=yes

- name: Get Kernel Release
  shell: uname -r
  ignore_errors: yes
  register: uname_result
  tags: [rails]

- name: install ruby dependencies
  action: apt pkg={{item}} state=installed
  with_items:
    - linux-headers-{{ uname_result.stdout }}
    - git-core
    - curl
    - zlib1g-dev
    - build-essential
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - python-software-properties
    - libffi-dev
  tags: [rails]

- name: Install app dependencies
  action: apt pkg={{item}} state=installed
  with_items:
    - nodejs
  tags: [rails]

# Install correct version of ruby from source
- name: ruby-from-src | ensure directory temporary ruby download directory is present
  file: state=directory path={{rubyTmpDir}}

- name: ruby-from-src | Download ruby source
  get_url: url={{rubyUrl}} dest={{rubyTmpDir}}

- name: ruby-from-src | ensure ruby is extracted
  command: tar -xf {{rubyCompressedFile}} chdir={{rubyTmpDir}} creates={{tmpRubyPath}}

- name: ruby-from-src | ensure ruby is configured
  command: ./configure chdir={{tmpRubyPath}} creates={{tmpRubyPath}}/Makefile

- name: ruby-from-src | ensure ruby is compiled
  command: make chdir={{tmpRubyPath}} creates={{tmpRubyPath}}/ruby

- name: ruby-from-src | ensure ruby is installed
  command: make install chdir={{tmpRubyPath}} creates=/usr/local/bin/ruby
- name: Install Rails
  command: gem install rails
